/**
 * OpenClaw Adapter
 *
 * Emits an OpenClaw plugin structure:
 *   .openclaw/rune/openclaw.plugin.json  (manifest)
 *   .openclaw/rune/src/index.ts          (register entrypoint)
 *   .openclaw/rune/skills/*.md           (transformed skill files)
 *
 * Follows the NeuralMemory OpenClaw plugin pattern.
 */

const TOOL_MAP = {
  Read: 'read_file',
  Write: 'write_file',
  Edit: 'edit_file',
  Glob: 'glob',
  Grep: 'grep',
  Bash: 'run_command',
  TodoWrite: 'todo_write',
  Skill: 'follow the referenced skill',
  Agent: 'execute the workflow',
};

export default {
  name: 'openclaw',
  outputDir: '.openclaw/rune/skills',
  fileExtension: '.md',
  skillPrefix: 'rune-',
  skillSuffix: '',

  transformReference(skillName, raw) {
    const isBackticked = raw.startsWith('`') && raw.endsWith('`');
    const ref = `rune-${skillName}.md`;
    return isBackticked ? `\`${ref}\`` : ref;
  },

  transformToolName(toolName) {
    return TOOL_MAP[toolName] || toolName;
  },

  generateHeader(skill) {
    return `# rune-${skill.name}\n\n> Rune ${skill.layer} Skill | ${skill.group}\n\n`;
  },

  generateFooter() {
    return [
      '',
      '---',
      '> **Rune Skill Mesh** — 55 skills, 200+ connections',
      '> Source: https://github.com/rune-kit/rune',
    ].join('\n');
  },

  transformSubagentInstruction(text) {
    return text;
  },

  postProcess(content) {
    return content
      .replace(/^context: fork\n/gm, '')
      .replace(/^agent: general-purpose\n/gm, '');
  },

  /**
   * Generate openclaw.plugin.json manifest
   *
   * @param {object[]} skills - parsed skill objects
   * @param {object} pluginJson - Rune's .claude-plugin/plugin.json
   * @returns {object} manifest object
   */
  generateManifest(skills, pluginJson) {
    return {
      id: 'rune',
      name: 'Rune',
      kind: 'skills',
      description: '55-skill mesh for AI coding assistants. Routes all code tasks through specialized skills.',
      version: pluginJson.version || '0.0.0',
      skills: ['./skills'],
      configSchema: {
        jsonSchema: {
          type: 'object',
          properties: {
            disabledSkills: {
              type: 'array',
              items: { type: 'string' },
              description: 'Skills to disable (by name)',
              default: [],
            },
          },
          additionalProperties: false,
        },
        uiHints: {
          disabledSkills: {
            label: 'Disabled Skills',
            help: 'Comma-separated list of skill names to exclude from routing',
          },
        },
      },
    };
  },

  /**
   * Generate src/index.ts entry point with register(api) pattern
   *
   * @param {object[]} skills - parsed skill objects
   * @param {string} routerContent - skill-router SKILL.md content for injection
   * @returns {string} TypeScript source
   */
  generateEntryPoint(skills, routerContent) {
    const skillNames = skills.map(s => s.name);
    const routingTable = skills
      .map(s => `//   ${s.name} (${s.layer}) — ${s.description || s.group}`)
      .join('\n');

    // Escape backticks and backslashes in router content for template literal
    const escapedRouter = (routerContent || '')
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$');

    return `/**
 * Rune — OpenClaw Plugin Entry Point
 *
 * Auto-generated by Rune compiler.
 * Do not edit manually — regenerate with: rune build --platform openclaw
 *
 * Skills (${skillNames.length}):
${routingTable}
 */

const SKILL_ROUTER_INSTRUCTIONS = \`${escapedRouter}\`;

const plugin = {
  id: 'rune',
  name: 'Rune',

  register(api: any): void {
    // Inject skill-router instructions so the agent routes through Rune skills
    api.on('before_agent_start', async () => {
      return {
        prependSystemContext: SKILL_ROUTER_INSTRUCTIONS,
      };
    }, { priority: 5 });
  },
};

export default plugin;
`;
  },
};
